const bcrypt=require('bcryptjs');
const Student=require('../models/StudentEnrollment');
const Assignment=require('../models/Assignment');
const Attendance=require('../models/Attendance');
const StudyMaterial=require('../models/StudyMaterial');
const Test=require('../models/Test');
const Schedule=require('../models/Schedule');
const Notification=require('../models/Notification');
const Message=require('../models/Message');
const Progress=require('../models/Progress');
const User=require('../models/User');
const TutorChangeRequest=require('../models/TutorChangeRequest');

async function getStudent(req){return Student.findOne({user:req.session.user.id,isDeleted:{$ne:true}}).populate('assignedTutor');}
exports.dashboard=async(req,res)=>{try{const student=await getStudent(req);if(!student)return res.render('dashboard/complete-profile',{title:'Complete Your Profile',user:req.session.user});const [assignments,attendance,materials,tests,notifications,schedules,progress]=await Promise.all([Assignment.find({student:student._id}).sort({createdAt:-1}),Attendance.find({student:student._id}).sort({date:-1}),StudyMaterial.find({tutor:student.assignedTutor?._id}).sort({createdAt:-1}),Test.find({student:student._id}).sort({testDate:1}),Notification.find({user:req.session.user.id}).sort({createdAt:-1}).limit(10),Schedule.find({student:student._id}).sort({createdAt:-1}),Progress.find({student:student._id}).sort({createdAt:-1})]);res.render('dashboard/student-dashboard',{title:'Student Dashboard',student,assignments,attendance,materials,tests,notifications,schedules,progress,user:req.session.user});}catch(e){console.log(e);res.status(500).send('Server Error')}};
exports.profile=async(req,res)=>{try{const student=await getStudent(req);if(!student)return res.redirect('/enroll-student');res.render('dashboard/student-profile',{title:'My Profile',student,user:req.session.user});}catch(e){res.status(500).send('Server Error')}};
exports.updateProfile=async(req,res)=>{try{const student=await getStudent(req);if(!student)return res.redirect('/enroll-student');Object.assign(student,{studentName:req.body.studentName,class:req.body.class,subject:req.body.subject,school:req.body.school,board:req.body.board,medium:req.body.medium,duration:req.body.duration,timeSlot:req.body.timeSlot,currentLocation:req.body.currentLocation,landmark:req.body.landmark,permanentAddress:req.body.permanentAddress,parentName:req.body.parentName,parentOccupation:req.body.parentOccupation,studentContact:req.body.studentContact,parentContact:req.body.parentContact,whatsappNumber:req.body.whatsappNumber,email:req.body.email});await student.save();res.redirect('/student/profile');}catch(e){console.log(e);res.status(500).send('Server Error')}};
exports.assignments=async(req,res)=>{const student=await getStudent(req);if(!student)return res.redirect('/student/dashboard');const assignments=await Assignment.find({student:student._id}).populate('tutor').sort({createdAt:-1});res.render('dashboard/student-assignments',{title:'Assignments',student,assignments,user:req.session.user});};
exports.submitAssignment=async(req,res)=>{const student=await getStudent(req);await Assignment.findOneAndUpdate({_id:req.params.id,student:student._id},{submission:req.body.submission,status:'submitted',submittedAt:new Date()});res.redirect('/student/assignments');};
exports.attendance=async(req,res)=>{const student=await getStudent(req);const attendance=await Attendance.find({student:student._id}).sort({date:-1});res.render('dashboard/student-attendance',{title:'Attendance',student,attendance,user:req.session.user});};
exports.materials=async(req,res)=>{const student=await getStudent(req);const materials=await StudyMaterial.find({tutor:student.assignedTutor?._id}).sort({createdAt:-1});res.render('dashboard/student-materials',{title:'Study Materials',student,materials,user:req.session.user});};
exports.tests=async(req,res)=>{const student=await getStudent(req);const tests=await Test.find({student:student._id}).sort({testDate:1});res.render('dashboard/student-tests',{title:'Tests',student,tests,user:req.session.user});};
exports.schedule=async(req,res)=>{const student=await getStudent(req);const schedules=await Schedule.find({student:student._id}).sort({createdAt:-1});res.render('dashboard/student-schedule',{title:'Schedule',student,schedules,user:req.session.user});};
exports.progress=async(req,res)=>{const student=await getStudent(req);const progress=await Progress.find({student:student._id}).sort({createdAt:-1});res.render('dashboard/student-progress',{title:'Progress',student,progress,user:req.session.user});};
exports.notifications=async(req,res)=>{const notifications=await Notification.find({user:req.session.user.id}).sort({createdAt:-1});await Notification.updateMany({user:req.session.user.id},{read:true});res.render('dashboard/notifications',{title:'Notifications',notifications,user:req.session.user});};
exports.messages=async(req,res)=>{const messages=await Message.find({$or:[{sender:req.session.user.id},{recipient:req.session.user.id}]}).populate('sender recipient').sort({createdAt:1});const tutor=await getStudent(req);res.render('dashboard/messages',{title:'Messages',messages,recipient:tutor.assignedTutor?.user||null,user:req.session.user});};
exports.sendMessage=async(req,res)=>{if(!req.body.body)return res.redirect('/student/messages');const student=await getStudent(req);if(student.assignedTutor?.user)await Message.create({sender:req.session.user.id,recipient:student.assignedTutor.user,body:req.body.body});res.redirect('/student/messages');};
exports.requestTutorChange=async(req,res)=>{try{const student=await getStudent(req);if(!student||!student.assignedTutor)return res.redirect('/student/dashboard');await TutorChangeRequest.create({student:student._id,currentTutor:student.assignedTutor._id,reason:req.body.reason});if(student.user)await Notification.create({user:student.user,title:'Tutor change request submitted',message:'Your request has been sent to the administrator.'});res.redirect('/student/profile');}catch(e){console.log(e);res.status(500).send('Server Error')}};
exports.changePassword=async(req,res)=>{try{if(req.body.password!==req.body.confirmPassword)return res.status(400).send('Passwords do not match');const user=await User.findById(req.session.user.id);if(!user)return res.redirect('/login');if(!(await bcrypt.compare(req.body.currentPassword,user.password)))return res.status(400).send('Current password is incorrect');user.password=await bcrypt.hash(req.body.password,10);await user.save();res.redirect('/student/profile');}catch(e){res.status(500).send('Server Error')}};
